all: checkEnv clean matrix_add_cpu

.PHONY: checkEnv clean

#module purge; module load cgpu; module load gcc/8.3.0; module load cuda/11.0.3; module load openmpi/4.0.3

matrix_add_cpu: matrix_add_cpu.c
	gcc -O3 -Wall -g matrix_add_cpu.c -o matrix_add_cpu -I${OPENMPI_DIR}/include -L${OPENMPI_DIR}/lib -lmpi -DPROFILING

clean:
	rm -f matrix_add_cpu

